'use strict'

const test = require('node:test')
const assert = require('node:assert/strict')
const { readFileSync } = require('node:fs')
const path = require('node:path')

test('agent composer multi-selects data, scripts, knowledge and Skills into removable chips', () => {
  const app = readFileSync(path.join(__dirname, '..', 'src', 'App.tsx'), 'utf8')
  const css = readFileSync(path.join(__dirname, '..', 'src', 'styles', 'app.css'), 'utf8')
  const menu = app.slice(app.indexOf('<details className="composer-menu data-menu"'), app.indexOf('<details className="composer-menu capability-menu"'))
  assert.doesNotMatch(menu, /type="checkbox"/)
  assert.match(menu, /<ResourceGroup title="数据库"/)
  assert.match(menu, /<ResourceGroup title="脚本"/)
  assert.match(menu, /<ResourceGroup title="知识库"/)
  assert.match(app, /function ResourceGroup/)
  assert.match(app, /aria-label="选择 Skill"/)
  assert.match(app, /className="composer-selections"/)
  assert.match(app, /data-kind=\{item\.kind\}/)
  assert.match(app, /data-kind=\{item\.type === 'skill' \? 'skill' : 'attachment'\}/)
  assert.match(app, /document\.addEventListener\('pointerdown', closeOutside, true\)/)
  assert.match(css, /\.composer-selections[^}]*overflow-x: auto/)
  assert.match(css, /\.selection-chip[^}]*flex: 0 0 auto/)
})

test('conversation selection and composer focus stay neutral while history labels use available width', () => {
  const css = readFileSync(path.join(__dirname, '..', 'src', 'styles', 'app.css'), 'utf8')
  const main = readFileSync(path.join(__dirname, '..', 'desktop', 'main.cjs'), 'utf8')
  assert.match(css, /#root \.conversation-history-card \.conversation-list-item\[data-active="true"\] \{ background: transparent !important; \}/)
  assert.match(css, /\.conversation-select strong \{[^}]*font-family: var\(--font-body\);[^}]*font-weight: 400;/)
  assert.match(css, /\.conversation-list-item \{[^}]*transition: none;/)
  assert.match(css, /\.conversation-item-actions \{[^}]*position: absolute;[^}]*padding: 0;[^}]*background: transparent;[^}]*transition: none;/)
  assert.match(css, /\.conversation-select \{[^}]*width: 100%;/)
  assert.doesNotMatch(css, /\.conversation-list-item:hover \.conversation-select/)
  assert.match(css, /#root \.composer-box,\s*#root \.composer-box:hover,\s*#root \.composer-box:focus,\s*#root \.composer-box:focus-within \{[^}]*box-shadow: none !important;[^}]*transition: none !important;/)
  assert.match(css, /#root \.composer textarea,\s*#root \.composer textarea:hover,\s*#root \.composer textarea:focus,\s*#root \.composer textarea:focus-visible \{[^}]*background: transparent !important;[^}]*box-shadow: none !important;/)
  assert.match(css, /#root \.conversation-item-actions,\s*#root \.conversation-item-actions:hover \{[^}]*background: transparent !important;[^}]*box-shadow: none !important;[^}]*transition: none !important;/)
  assert.match(css, /#root \.conversation-item-actions button,[\s\S]*#root \.conversation-item-actions button:focus-visible \{[^}]*background: transparent !important;[^}]*box-shadow: none !important;[^}]*transition: none !important;/)
  assert.match(main, /STABLE_QA_AGENT_NEUTRAL_STATES/)
})

test('paperclip separates ordinary file, ZIP and folder attachments from Skill installation', () => {
  const app = readFileSync(path.join(__dirname, '..', 'src', 'App.tsx'), 'utf8')
  const main = readFileSync(path.join(__dirname, '..', 'desktop', 'main.cjs'), 'utf8')
  const preload = readFileSync(path.join(__dirname, '..', 'desktop', 'preload.cjs'), 'utf8')
  assert.match(app, /accept="[^"]*\.zip"/)
  assert.match(app, /window\.stable\.agent\.selectAttachmentFolder\(\)/)
  assert.match(app, />普通文件夹</)
  assert.match(app, />安装新的 Skill 文件夹</)
  assert.match(preload, /stable:agent:selectAttachmentFolder/)
  assert.match(main, /inspectAttachmentPath/)
  assert.match(main, /materializeAttachment\(item\.path, attachmentRoot\)/)
  assert.match(main, /extractAgentAttachments\(payload\?\.attachments, conversationId\)/)
  assert.match(main, /stable:agent:selectAttachmentFolder/)
  assert.match(main, /const \{ content: _content, description: _description, \.\.\.item \} = inspectSkillFolder/)
  assert.match(main, /skillPaths\.has\(inspected\[index\]\.path\)\) inspected\[index\] = inspectSkillFolder/)
})

test('sent attachments leave the composer, follow the user message, and completed traces have no summary', () => {
  const app = readFileSync(path.join(__dirname, '..', 'src', 'App.tsx'), 'utf8')
  const css = readFileSync(path.join(__dirname, '..', 'src', 'styles', 'app.css'), 'utf8')
  assert.match(app, /setPrompt\(''\); setAttachments\(\[\]\); setReferences\(\[\]\)/)
  assert.match(app, /setPendingMap\(\(current\) => \(\{ \.\.\.current, \[conversationId\]: \{ content: value, attachments: messageAttachments \} \}\)\)/)
  assert.match(app, /window\.stable\.agent\.configure\(conversationId, activeConversation\.capability, \[\]\)/)
  assert.match(app, /window\.stable\.agent\.run\(conversationId, value, currentAttachments, currentReferences\)/)
  assert.match(app, /<UserTurn content=\{message\.content\} attachments=\{message\.attachments\}/)
  assert.match(app, /className="message-attachments"/)
  assert.match(css, /\.message-attachments[^}]*overflow-x: auto/)
  const trace = app.slice(app.indexOf('function RunTrace'), app.indexOf('function markdownTableCells'))
  assert.match(trace, /if \(status === 'completed'\) setExpanded\(false\)/)
  assert.match(app, /function TraceModuleCard/)
  assert.match(app, /new Map<AgentTraceKind, AgentTraceItem\[\]>/)
  assert.match(app, /window\.setInterval\([\s\S]*2000\)/)
  assert.match(app, /onMouseEnter=\{\(\) => setPaused\(true\)\}/)
  assert.match(trace, /<TraceModuleCard kind=\{kind\} items=\{moduleItems\} key=\{kind\}/)
  assert.match(css, /\.trace-card-grid/)
  assert.match(css, /@keyframes trace-card-swap/)
  assert.doesNotMatch(trace, /toolCount|duration|const summary|<small>\{summary\}<\/small>/)
})

test('agent conversations run independently and keep a persisted permission mode', () => {
  const app = readFileSync(path.join(__dirname, '..', 'src', 'App.tsx'), 'utf8')
  const main = readFileSync(path.join(__dirname, '..', 'desktop', 'main.cjs'), 'utf8')
  const preload = readFileSync(path.join(__dirname, '..', 'desktop', 'preload.cjs'), 'utf8')
  const store = readFileSync(path.join(__dirname, '..', 'desktop', 'services', 'store.cjs'), 'utf8')
  assert.match(app, /runningMap/)
  assert.match(app, /traceMap/)
  assert.match(app, /pendingMap/)
  assert.match(app, /PERMISSION_OPTIONS/)
  assert.match(app, /请求审批/)
  assert.match(app, /帮我审批/)
  assert.match(app, /完全访问权限/)
  assert.match(app, /<ApprovalCard/)
  assert.match(app, /window\.stable\.agent\.cancel\(activeConversation\.id\)/)
  assert.match(main, /const agentRunners = new Map\(\)/)
  assert.match(main, /agentRunners\.has\(conversationId\)/)
  assert.match(main, /new Set\(\)/)
  assert.match(main, /stable:agent:answerApproval/)
  assert.match(preload, /stable:agent:configurePermission/)
  assert.match(preload, /stable:agent:answerApproval/)
  assert.match(store, /permission_mode TEXT NOT NULL DEFAULT 'full'/)
  assert.match(main, /publishAgentState\(conversationId\)/)
  assert.match(preload, /stable:agent:state/)
  assert.match(store, /updateConversationPermission/)
})

test('conversation installs Skill folders globally and the Skill library is preview-only cards', () => {
  const app = readFileSync(path.join(__dirname, '..', 'src', 'App.tsx'), 'utf8')
  const main = readFileSync(path.join(__dirname, '..', 'desktop', 'main.cjs'), 'utf8')
  const preload = readFileSync(path.join(__dirname, '..', 'desktop', 'preload.cjs'), 'utf8')
  const css = readFileSync(path.join(__dirname, '..', 'src', 'styles', 'app.css'), 'utf8')
  const skillsPage = app.slice(app.indexOf('function SkillsPage'), app.indexOf('function PageLead'))
  assert.match(app, /window\.stable\.agent\.selectSkillFolder\(\)/)
  assert.match(app, /aria-label="选择 Skill"/)
  assert.match(app, /安装新的 Skill 文件夹/)
  assert.match(app, /item\.type === 'skill' \? 'skill'/)
  assert.match(preload, /stable:agent:selectSkillFolder/)
  assert.match(main, /requirePaths\(inputPaths, '临时附件', 8\)\.map\(inspectAttachmentPath\)/)
  assert.match(main, /importSkillFolder\(item\.path, path\.join\(paths\.userData, 'skills'\)\)/)
  assert.match(main, /title: '安装全局 Skill'/)
  assert.doesNotMatch(skillsPage, /DropTarget|导入 Skill|importFolder|importPaths/)
  assert.match(skillsPage, /className="skill-card-grid"/)
  assert.match(skillsPage, /className="skill-preview-button"/)
  assert.match(skillsPage, /SKILL\.md · RAW/)
  assert.match(skillsPage, /<pre tabIndex=\{0\}><code>\{preview\.content\}<\/code><\/pre>/)
  assert.match(css, /\.skill-card-grid/)
  assert.match(css, /\.skill-card:hover,[\s\S]*box-shadow: var\(--shadow-hover\)/)
  assert.match(css, /\.skill-preview-dialog pre/)
})

test('workflow page is a resource-backed editable topology and conversation has no collaboration graph', () => {
  const app = readFileSync(path.join(__dirname, '..', 'src', 'App.tsx'), 'utf8')
  const studio = readFileSync(path.join(__dirname, '..', 'src', 'WorkflowStudio.tsx'), 'utf8')
  const css = readFileSync(path.join(__dirname, '..', 'src', 'styles', 'app.css'), 'utf8')
  assert.doesNotMatch(app, /collaboration-toggle|AgentGraph|团队执行/)
  assert.match(app, /<WorkflowStudio state=\{state\}/)
  assert.match(studio, /ReactFlow/)
  assert.match(studio, /data: \{ label: '数据'/)
  assert.match(studio, /knowledge: \{ label: '知识库'/)
  assert.match(studio, /script: \{ label: '脚本'/)
  assert.match(studio, /skill: \{ label: 'Skill'/)
  assert.match(studio, /ai: \{ label: 'AI 运算'/)
  assert.match(studio, /output: \{ label: '输出'/)
  assert.match(studio, /window\.stable\.workflows\.generate\(goal\)/)
  assert.match(studio, /createsCycle/)
  assert.match(app, /data-page="workflows" hidden=\{page !== 'workflows'\}/)
  assert.match(studio, /type="target" position=\{Position\.Left\}/)
  assert.match(studio, /type="source" position=\{Position\.Right\}/)
  assert.match(studio, /className="workflow-module-title nodrag nopan"/)
  assert.match(studio, /className="workflow-dock"/)
  assert.match(studio, /aria-label="AI 生成工作流"/)
  assert.match(studio, /aria-label="工作流库"/)
  assert.match(studio, /type: 'workflow'/)
  assert.match(studio, /BaseEdge/)
  assert.match(studio, /getBezierPath/)
  assert.match(studio, /edgeTypes=\{EDGE_TYPES\}/)
  assert.match(studio, /className="workflow-node-editor"/)
  assert.match(studio, /data-expanded=\{editorExpanded/)
  assert.match(studio, /aria-label="AI 处理深度"/)
  assert.match(studio, /onMove=\{\(\) => \{ if \(selectedEditorNodeId && !editorExpanded\) positionEditor\(selectedEditorNodeId\) \}\}/)
  const positionEditor = studio.slice(studio.indexOf('const positionEditor'), studio.indexOf('const selectedTextNode'))
  assert.match(positionEditor, /nodeRect\.left - canvasRect\.left \+ \(nodeRect\.width - width\) \/ 2/)
  assert.doesNotMatch(positionEditor, /Math\.max|Math\.min\(nodeRect\.left/)
  assert.match(studio, /aria-label="模块 AI 输入"/)
  assert.match(studio, /event\.nativeEvent\.isComposing/)
  assert.match(studio, /window\.stable\.workflows\.enhanceInstruction/)
  assert.match(studio, /className="workflow-module-copy/)
  assert.doesNotMatch(studio, /aria-label="运算指令"/)
  assert.doesNotMatch(studio, /aria-label="输出文件名"/)
  assert.match(studio, /Markdown 文档 \(\.md\)/)
  assert.match(studio, /PowerPoint 演示文稿 \(\.pptx\)/)
  assert.match(studio, /Excel 工作簿 \(\.xlsx\)/)
  assert.doesNotMatch(studio, /className="button" disabled=\{Boolean\(busy\)\}/)
  assert.match(studio, /workflow-flow-streak workflow-flow-streak-aura/)
  assert.match(studio, /workflow-flow-streak workflow-flow-streak-core/)
  assert.match(studio, /function edgeMotion\(id: string\)/)
  assert.match(studio, /hash = 2166136261[\s\S]*Math\.imul\(hash, 16777619\)[\s\S]*hash \^= hash >>> 16/)
  assert.match(studio, /const duration = 820 \+ seed % 781/)
  assert.match(studio, /delay: -\(seed >>> 8\) % duration/)
  assert.match(studio, /measureRef\.current\?\.getTotalLength\(\)/)
  assert.match(studio, /const segmentLength = measuredLength \* 0\.7/)
  assert.match(studio, /'--workflow-flow-dash': `\$\{segmentLength\}px \$\{measuredLength\}px`/)
  assert.match(studio, /Math\.min\(10, 1 \+ elapsedSeconds\)/)
  assert.match(studio, /animation\.updatePlaybackRate\(rate\)/)
  assert.match(studio, /window\.setInterval\([\s\S]*1000\)/)
  assert.doesNotMatch(studio, /<animate /)
  assert.doesNotMatch(studio, /animateMotion|workflow-flow-particle|<circle/)
  assert.match(css, /\.react-flow__edge-path[^}]*stroke: var\(--color-workflow-edge\)/)
  assert.match(css, /\.workflow-flow-streak[^}]*stroke: var\(--color-workflow-flow\)/)
  assert.match(css, /\.react-flow__edge\.animated \.workflow-flow-streak[^}]*stroke-dasharray: var\(--workflow-flow-dash\)[^}]*animation: workflow-flow-travel var\(--workflow-flow-duration\) linear infinite/)
  assert.match(css, /@keyframes workflow-flow-travel \{ from \{ stroke-dashoffset: var\(--workflow-flow-start\); \} to \{ stroke-dashoffset: var\(--workflow-flow-end\); \} \}/)
  const workflowFlowCss = css.slice(
    css.indexOf('.workflow-canvas .workflow-flow-streaks'),
    css.indexOf('.workflow-canvas .react-flow__connection-path'),
  )
  assert.doesNotMatch(workflowFlowCss, /filter:/)
  assert.doesNotMatch(css, /\.react-flow__edge\.animated path \{ animation-duration: 0\.05s; \}/)
  assert.match(css, /\.react-flow__edge\.selected \.react-flow__edge-path/)
  assert.match(css, /\.workflow-node-editor/)
  assert.match(css, /\.workflow-library-picker \{ inset-inline-start: calc\(17rem - 1px\)/)
  assert.doesNotMatch(studio, /workflow-studio-index|workflow-inspector|workflow-ai-builder/)
})

test('workflow execution can stop, keeps semi-automatic scripts alive, auto names outputs and deletes only selected edges', () => {
  const studio = readFileSync(path.join(__dirname, '..', 'src', 'WorkflowStudio.tsx'), 'utf8')
  const main = readFileSync(path.join(__dirname, '..', 'desktop', 'main.cjs'), 'utf8')
  const preload = readFileSync(path.join(__dirname, '..', 'desktop', 'preload.cjs'), 'utf8')
  assert.match(studio, /workflowRunning \? <button className="button danger"/)
  assert.match(studio, /window\.stable\.workflows\.cancel\(\)/)
  assert.match(studio, /selected: edge\.id === selectedEdgeId/)
  assert.match(studio, /onEdgeClick=/)
  assert.match(studio, /onEdgeContextMenu=/)
  assert.match(studio, /onEdgesDelete=\{\(edges\) => removeEdges/)
  assert.match(studio, /edges: current\.edges\.filter/)
  const workflowRun = main.slice(main.indexOf('async function runWorkflow'), main.indexOf('function cancelWorkflow'))
  assert.doesNotMatch(workflowRun, /const timer = setTimeout/)
  assert.match(workflowRun, /idleNoticeMs: 5 \* 60_000/)
  assert.match(workflowRun, /confirm: false/)
  assert.match(main, /createScriptAutoResponder/)
  assert.match(main, /runOptions\.confirm !== false/)
  assert.match(main, /STABLE_QA_WORKFLOW_PAN/)
  assert.match(main, /STABLE_QA_WORKFLOW_EDGE_RUNNING/)
  assert.match(main, /workflowEditorAnchor/)
  assert.doesNotMatch(main, /sendWorkflowScriptInput|pendingScriptInput|requiresConfirmation|STABLE_QA_WORKFLOW_CONFIRMATION/)
  assert.doesNotMatch(studio, /selectedScriptConfirmation|workflow-script-confirm|控制台确认输入/)
  assert.match(main, /function cancelWorkflow\(\)/)
  assert.match(main, /timestampedOutputName\(outputName\)/)
  assert.match(workflowRun, /scheduleWorkflowTasks\(graph, executeNode\)/)
  assert.match(workflowRun, /new ScriptRunner\(\{ workspace: paths\.workspace \}\)/)
  assert.match(workflowRun, /const aiRunner = createHarnessRunner\(\)/)
  assert.doesNotMatch(workflowRun, /result = await runner\.run\(/)
  const outputBranch = workflowRun.slice(workflowRun.indexOf("node.type === 'output'"))
  assert.doesNotMatch(outputBranch, /runner\.run\(/)
  assert.match(outputBranch, /writeWorkflowOutput\(/)
  assert.doesNotMatch(main, /node\.outputName \|\| workflow\.name/)
  assert.match(main, /recoverInterruptedRuns\(\)/)
  assert.match(preload, /stable:workflows:cancel/)
  assert.match(preload, /stable:workflows:enhanceInstruction/)
  assert.doesNotMatch(preload, /stable:workflows:scriptInput/)
})

test('module prompt creation is per-node and every existing edge animates for the full workflow run', () => {
  const studio = readFileSync(path.join(__dirname, '..', 'src', 'WorkflowStudio.tsx'), 'utf8')
  const main = readFileSync(path.join(__dirname, '..', 'desktop', 'main.cjs'), 'utf8')
  const enhancement = studio.slice(studio.indexOf('async function enhanceSelectedNode'), studio.indexOf('async function removeWorkflow'))
  assert.match(studio, /AI提示词创作中/)
  assert.match(studio, /enhancementRunsRef/)
  assert.match(studio, /enhancingNodeIds\.has\(item\.id\)/)
  assert.match(enhancement, /window\.stable\.workflows\.enhanceInstruction/)
  assert.doesNotMatch(enhancement, /action\(/)
  assert.match(studio, /animated: workflowRunning/)
  assert.doesNotMatch(studio, /animated: statuses\[edge\.target\]/)
  assert.match(main, /const instructionRunner = createHarnessRunner\(\)/)
})

test('completed workflow outputs expose a temporary connected exit node with file actions', () => {
  const studio = readFileSync(path.join(__dirname, '..', 'src', 'WorkflowStudio.tsx'), 'utf8')
  const main = readFileSync(path.join(__dirname, '..', 'desktop', 'main.cjs'), 'utf8')
  const preload = readFileSync(path.join(__dirname, '..', 'desktop', 'preload.cjs'), 'utf8')
  assert.match(main, /artifacts\.push\(\{ nodeId, path: output\.path, name: path\.basename\(output\.path\) \}\)/)
  assert.match(main, /return \{ output, artifacts, workflows:/)
  assert.match(studio, /function ExitNode/)
  assert.match(studio, /if \(!result\.cancelled\) setArtifacts\(result\.artifacts \|\| \[\]\)/)
  assert.match(studio, /source: artifact\.nodeId, target: `exit-\$\{artifact\.nodeId\}`/)
  assert.match(studio, />打开文件<\/button>/)
  assert.match(studio, />打开所在文件夹<\/button>/)
  assert.match(preload, /stable:system:showItemInFolder/)
})

test('agent runs refresh Stable native resource status in the shared app state', () => {
  const main = readFileSync(path.join(__dirname, '..', 'desktop', 'main.cjs'), 'utf8')
  assert.match(main, /library: store\.listLibrary\(\), skills: store\.listSkills\(\), workflows: store\.listWorkflows\(\)/)
})

test('assistant Markdown tables keep stable hover geometry and expose Markdown-only copy', () => {
  const app = readFileSync(path.join(__dirname, '..', 'src', 'App.tsx'), 'utf8')
  const css = readFileSync(path.join(__dirname, '..', 'src', 'styles', 'app.css'), 'utf8')
  assert.match(app, /function isMarkdownTableStart/)
  assert.match(app, /className="markdown-table-wrap"/)
  assert.match(app, /className="markdown-table-copy"/)
  assert.match(app, /window\.stable\.clipboard\.writeText\(markdownTableSource\(headers, separators, rows\)\)/)
  assert.match(app, /<table><thead><tr>/)
  assert.match(css, /\.markdown-table-wrap[^}]*overflow-x: auto/)
  assert.match(css, /\.markdown-table-shell:hover \.markdown-table-copy/)
  const hoverLift = css.slice(css.indexOf('@media (hover: hover) and (pointer: fine)', css.indexOf('.markdown-table-shell')), css.indexOf('#root :where(', css.indexOf('.markdown-table-shell')))
  assert.doesNotMatch(hoverLift, /\.markdown-table-wrap/)
  assert.match(css, /\.markdown-body table/)
  assert.match(css, /\.markdown-body \{[^}]*width: 100%;[^}]*max-width: none/)
  assert.match(css, /\.assistant-answer \.markdown-body \{[^}]*font-family: "Microsoft YaHei", "微软雅黑", sans-serif;[^}]*font-size: var\(--text-sm\)/)
  assert.match(css, /\.assistant-answer \.markdown-body h2 \{[^}]*font-family: inherit;[^}]*font-size: var\(--text-md\)/)
})

test('agent page stays mounted across tabs and each answer has only one execution module above it', () => {
  const app = readFileSync(path.join(__dirname, '..', 'src', 'App.tsx'), 'utf8')
  assert.match(app, /data-page="agent" hidden=\{page !== 'agent'\}/)
  assert.doesNotMatch(app, /page === 'agent' && <AgentPage/)
  const turn = app.slice(app.indexOf('function MessageTurn'), app.indexOf('function UserTurn'))
  assert.match(turn, /<RunTrace items=\{message\.trace\}/)
  assert.match(turn, /<MarkdownContent content=\{message\.content\}/)
  assert.doesNotMatch(turn, /分析过程|analysis-process|splitAssistantAnswer/)
  assert.ok(turn.indexOf('<RunTrace') < turn.indexOf('assistant-answer'))
})

test('home lead keeps the requested three fixed lines', () => {
  const app = readFileSync(path.join(__dirname, '..', 'src', 'App.tsx'), 'utf8')
  const css = readFileSync(path.join(__dirname, '..', 'src', 'styles', 'app.css'), 'utf8')
  assert.match(app, /<span>AI_Native助力业务流程优化<\/span><span>本地部署的Agent助理，确保数据安全<\/span><span>数据存储库致力专注<\/span>/)
  assert.match(css, /\.home-intro h2 > span[^}]*display: block[^}]*white-space: nowrap/)
})

test('sidebar brand logo follows the active light or dark theme', () => {
  const app = readFileSync(path.join(__dirname, '..', 'src', 'App.tsx'), 'utf8')
  const css = readFileSync(path.join(__dirname, '..', 'src', 'styles', 'app.css'), 'utf8')
  assert.match(app, /stable_logo_sidebar_dark\.png/)
  assert.match(app, /stable_logo_sidebar_light\.png/)
  assert.match(app, /state\.theme === 'light' \? sidebarLogoLightUrl : sidebarLogoDarkUrl/)
  assert.match(css, /\.brand-mark img \{[^}]*transform: translateY\(-6px\)/)
})

test('all script categories expose the shared console and components use borderless hover elevation', () => {
  const app = readFileSync(path.join(__dirname, '..', 'src', 'App.tsx'), 'utf8')
  const css = readFileSync(path.join(__dirname, '..', 'src', 'styles', 'app.css'), 'utf8')
  const dataLibrary = app.slice(app.indexOf('function DataPage'), app.indexOf('function ScriptCard'))
  assert.match(dataLibrary, /kind === 'script'\) setLogId\(event\.itemId\)/)
  assert.match(dataLibrary, /setRunningId\(item\.id\)\s+setLogId\(item\.id\)/)
  assert.match(dataLibrary, /logItem\?\.kind === 'script' && logItem\.category === section/)
  assert.doesNotMatch(dataLibrary, /section === 'collection' && logId/)
  assert.match(css, /#root \* \{[^}]*border: 0 !important;[^}]*box-shadow: none !important;/)
  assert.match(css, /#root :where\([\s\S]*\.workflow-module,[\s\S]*\):hover \{[\s\S]*box-shadow: var\(--shadow-hover\) !important;/)
})
