'use strict'

const test = require('node:test')
const assert = require('node:assert/strict')
const { readFileSync } = require('node:fs')
const path = require('node:path')

test('scheduled tasks replace overview and support manual, template and chat-confirmed creation', () => {
  const app = readFileSync(path.join(__dirname, '..', 'src', 'App.tsx'), 'utf8')
  const main = readFileSync(path.join(__dirname, '..', 'desktop', 'main.cjs'), 'utf8')
  const preload = readFileSync(path.join(__dirname, '..', 'desktop', 'preload.cjs'), 'utf8')
  assert.match(app, /\{ id: 'agent', label: '对话'/)
  assert.match(app, /\{ id: 'automations', label: '定时'/)
  assert.doesNotMatch(app.slice(app.indexOf('const NAV'), app.indexOf('function errorMessage')), /label: '总览'/)
  assert.match(app, /已配置/)
  assert.match(app, /执行历史/)
  assert.match(app, /任务模板/)
  assert.match(app, /手动新建/)
  assert.match(app, /在对话中创建/)
  assert.match(app, /确认创建/)
  assert.match(main, /setInterval\(checkDueAutomations, 15_000\)/)
  assert.match(main, /parseProposalOutput/)
  assert.match(preload, /stable:automations:proposal/)
})

test('GitHub Releases updater is configured for the Stable repository', () => {
  const app = readFileSync(path.join(__dirname, '..', 'src', 'App.tsx'), 'utf8')
  const updater = readFileSync(path.join(__dirname, '..', 'desktop', 'services', 'updater.cjs'), 'utf8')
  const installer = readFileSync(path.join(__dirname, '..', 'build', 'installer.nsh'), 'utf8')
  const installSection = readFileSync(path.join(__dirname, '..', 'build', 'stable-install-section.nsh'), 'utf8')
  const pkg = JSON.parse(readFileSync(path.join(__dirname, '..', 'package.json'), 'utf8'))
  assert.equal(pkg.version, '0.91.1')
  assert.deepEqual(pkg.build.publish[0], { provider: 'github', owner: 'LLucas88', repo: 'Stable', releaseType: 'release' })
  assert.equal(pkg.build.directories.output, 'release-0.91.1')
  assert.equal(pkg.build.compression, 'normal')
  assert.equal(pkg.build.nsis.oneClick, false)
  assert.equal(pkg.build.nsis.allowToChangeInstallationDirectory, true)
  assert.equal(pkg.build.nsis.useZip, false)
  assert.equal(pkg.build.nsis.differentialPackage, true)
  assert.match(app, /state\.update\.status === 'downloaded'[\s\S]*window\.stable\.updater\.install\(\)[\s\S]*安装更新/)
  assert.match(updater, /quitAndInstall\(false, false\)/)
  assert.doesNotMatch(updater, /scheduleInstall|autoInstallDelayMs/)
  assert.match(installer, /GetOptions[^\n]+--updated/)
  assert.match(installer, /SetSilent normal/)
  assert.match(installer, /--stable-update-quiet[\s\S]*SetSilent silent/)
  assert.match(pkg.build.nsis.script, /installer\.nsi$/)
  assert.match(installSection, /stableStageDir[\s\S]*Call stableInstallApplicationFiles[\s\S]*Rename "\$INSTDIR" "\$stablePreviousDir"[\s\S]*Rename "\$stableStageDir" "\$INSTDIR"/)
  assert.match(installSection, /SetOutPath "\$TEMP"[\s\S]*Rename "\$INSTDIR" "\$stablePreviousDir"/)
  assert.match(installSection, /--stable-update-healthcheck/)
  assert.match(installSection, /stableSwapRollback/)
  assert.match(installSection, /Call stableCheckAppRunning[\s\S]*stableHealthNewMoveFailed[\s\S]*stableHealthOldRestoreFailed/)
  assert.match(installSection, /QuietUninstallString[^\n]+_\?=\$INSTDIR/)
  assert.match(readFileSync(path.join(__dirname, '..', 'build', 'installer.nsi'), 'utf8'), /customUnInstall[\s\S]*STABLE_UNINSTALL_DIR[\s\S]*WindowStyle Hidden/)
  assert.match(readFileSync(path.join(__dirname, '..', 'desktop', 'main.cjs'), 'utf8'), /STABLE_UPDATE_FORCE_HEALTHCHECK_FAILURE/)
  const workflow = readFileSync(path.join(__dirname, '..', '.github', 'workflows', 'release.yml'), 'utf8')
  const installerQa = readFileSync(path.join(__dirname, 'verify-update-installer.ps1'), 'utf8')
  assert.match(workflow, /gh release download runtime-v1/)
  assert.match(workflow, /electron-builder --win --x64 --publish never/)
  assert.match(workflow, /npm run dist:update/)
  assert.match(workflow, /electron-builder --win --x64 --publish never[\s\S]+Full installer build failed/)
  assert.match(workflow, /npm run dist:update[\s\S]+Lightweight updater build failed/)
  assert.match(workflow, /verify-update-installer\.ps1/)
  assert.match(workflow, /release-0\.91\.1-update\/Stable-Update-0\.91\.1-x64\.exe/)
  assert.match(workflow, /timeout-minutes: 75/)
  assert.match(workflow, /Upload installer QA evidence/)
  assert.match(workflow, /GITHUB_EVENT_NAME[\s\S]+GITHUB_REF_TYPE[\s\S]+GITHUB_REF_NAME[\s\S]+does not match package version/)
  assert.match(workflow, /workflow_dispatch/)
  assert.match(workflow, /stable-update-installer-evidence/)
  assert.match(workflow, /if: success\(\) && github\.event_name == 'push' && github\.ref_type == 'tag'/)
  assert.match(workflow, /gh release upload \$tag \$assets .*--clobber/)
  assert.match(workflow, /gh release upload \$tag \$assets .*--clobber[\s\S]+Failed to upload one or more GitHub Release assets/)
  assert.match(workflow, /Stable-Update-\$version-x64\.exe\.blockmap/)
  assert.match(workflow, /"\$updateOutput\/latest\.yml"/)
  assert.match(installerQa, /RUNNER_ENVIRONMENT -ne 'github-hosted'/)
  assert.match(installerQa, /function Get-StableProductVersion[\s\S]+\[Version\]\$rawVersion/)
  assert.ok(installerQa.includes("Previous installer did not include its embedded Node runtime."))
  assert.match(installerQa, /function Restore-PreviousVersion[\s\S]+Remove-Item -LiteralPath \$runtimeDir -Recurse -Force[\s\S]+Assert-EmbeddedRuntimeReady/)
  assert.ok(installerQa.includes("Assert-PersistentRuntimeReady 'Successful update'"))
  assert.match(installerQa, /@\('--updated', '\/S', '--force-run', '\/currentuser'\)/)
  assert.match(installerQa, /ExpectedVersion/)
  assert.match(installerQa, /failure-diagnostics\.json/)
  assert.match(installerQa, /IsWindowVisible[\s\S]+msctls_progress32/)
  assert.match(installerQa, /function Wait-ForVisibleTerminal/)
  assert.match(installerQa, /\$updateTimeoutMs = 900000/)
  assert.match(installerQa, /function Get-UpdateInstallerProcesses[\s\S]+\[void\]\$candidate\.Handle/)
  assert.match(installerQa, /function Get-TerminalProgress[\s\S]+Get-Content -LiteralPath \$log[\s\S]+return \$lines\[-1\][\s\S]+Get-Content -LiteralPath \$progressFile -Raw/)
  assert.match(installerQa, /function Assert-VisibleInstallerWindow[\s\S]+\[bool\]\$allowDefaultTitle = \$false/)
  assert.match(installerQa, /\$allowDefaultTitle -and \$installerTitle -eq 'Stable Setup'/)
  assert.match(installerQa, /100%\.\*更新安装完成\.\*重新点击 Stable 图标/)
  assert.match(installerQa, /92%\.\*旧版本已恢复\.\*错误码 12/)
  const defaultTitleAllowances = installerQa.match(/Assert-VisibleInstallerWindow[^\r\n]*\$true/g) ?? []
  assert.equal(defaultTitleAllowances.length, 1)
  assert.match(defaultTitleAllowances[0], /\$failureProcess/)
  assert.match(installerQa, /Stop-Process -Id \$failureProcess\.Id -Force[\s\S]+WaitForExit\(10000\)/)
  assert.match(installerQa, /\$quietFailureProcessExitCode -ne 12/)
  assert.match(installerQa, /DisplayVersion[\s\S]+InstallLocation/)
  assert.match(installerQa, /Quiet rollback restored unexpected version/)
})
