'use strict'
const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const os = require('node:os')
const { executeExcel } = require('../desktop/services/excel-tool.cjs')
const { BuiltinTools } = require('../desktop/services/builtin-tools.cjs')
const { toolFile } = require('../desktop/services/tool-files.cjs')
const ExcelJS = require('../vendor/agent-tools/node_modules/exceljs')
const dependencyRoot = path.resolve(__dirname, '../vendor/agent-tools')

test('built-in Excel creates, reads, paginates and edits styled workbooks without changing the source', async t => {
  const workspace = fs.mkdtempSync(path.join(os.tmpdir(), 'stable-excel-test-'))
  t.after(() => fs.rmSync(workspace, { recursive: true, force: true }))
  const execute = args => executeExcel({ workspace, dependencyRoot, args })
  const result = await execute({ action: 'create', output: '销售.xlsx', sheets: [{ name: '销售', rows: [['门店', '销售额'], ['A店', 120], ['B店', 60], ['=literal', 1]] }, { name: '备注', rows: [['原件保留']] }] })
  assert.equal(result.verified, true)
  assert.equal(result.formulaCalculation, false)
  const original = fs.readFileSync(result.path)
  assert.deepEqual((await execute({ action: 'inspect', path: '销售.xlsx' })).sheets.map(s => s.name), ['销售', '备注'])
  const page = await execute({ action: 'read', path: '销售.xlsx', sheet: '销售', startRow: 2, rowCount: 1 })
  assert.deepEqual(page.rows, [{ row: 2, values: ['A店', 120] }]); assert.equal(page.nextRow, 3)
  await execute({ action: 'update', path: '销售.xlsx', output: '另存.xlsx', sheet: '销售', cells: [{ address: 'B2', value: 170, numFmt: '0.00' }, { address: 'B5', formula: 'SUM(B2:B3)' }] })
  assert.deepEqual(fs.readFileSync(result.path), original)
  const book = new ExcelJS.Workbook(); await book.xlsx.readFile(path.join(workspace, '另存.xlsx'))
  assert.equal(book.getWorksheet('销售').getCell('B2').value, 170)
  assert.equal(book.getWorksheet('销售').getCell('B2').numFmt, '0.00')
  assert.equal(book.getWorksheet('销售').getCell('A1').font.bold, true)
  assert.equal(book.getWorksheet('销售').getCell('A4').value, '=literal')
  assert.equal(book.getWorksheet('销售').getCell('B5').formula, 'SUM(B2:B3)')
  assert.equal(book.getWorksheet('备注').getCell('A1').value, '原件保留')
  await assert.rejects(execute({ action: 'create', output: '销售.xlsx', sheets: [{ name: 'x', rows: [[1]] }] }), /已存在/)
  await assert.rejects(execute({ action: 'read', path: '销售.xlsx', rowCount: 201 }), /200/)
  await assert.rejects(execute({ action: 'update', path: '销售.xlsx', output: '错误.xlsx', sheet: '销售', cells: [{ address: 'B2', formula: 'WEBSERVICE("https://example.com")' }] }), /公式/)
  assert.equal(fs.existsSync(path.join(workspace, '错误.xlsx')), false)
})

test('tool file boundaries reject traversal, ADS, links, overwrite and cancellation', async t => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'stable-tool-boundary-'))
  const workspace = path.join(root, 'workspace'); fs.mkdirSync(workspace)
  t.after(() => fs.rmSync(root, { recursive: true, force: true }))
  fs.writeFileSync(path.join(root, 'outside.xlsx'), 'fixture')
  fs.symlinkSync(root, path.join(workspace, 'escape'), 'junction')
  assert.throws(() => toolFile(workspace, '../outside.xlsx'), /工作区/)
  assert.throws(() => toolFile(workspace, 'a.xlsx:secret', { output: true }), /特殊/)
  assert.throws(() => toolFile(workspace, 'escape/outside.xlsx'), /越界/)
  assert.throws(() => toolFile(workspace, 'escape/new.xlsx', { output: true }), /工作区外/)
  const signal = AbortSignal.abort()
  await assert.rejects(executeExcel({ workspace, dependencyRoot, args: { action: 'create', output: 'cancel.xlsx', sheets: [{ name: 'x', rows: [[1]] }] }, signal }))
  assert.equal(fs.existsSync(path.join(workspace, 'cancel.xlsx')), false)
  const controller = new AbortController()
  const pending = executeExcel({ workspace, dependencyRoot, args: { action: 'create', output: 'cancel-active.xlsx', sheets: [{ name: 'x', rows: [[1]] }] }, signal: controller.signal })
  controller.abort(); await assert.rejects(pending, /取消/)
  assert.equal(fs.existsSync(path.join(workspace, 'cancel-active.xlsx')), false)
  const tools = new BuiltinTools({ workspace })
  await assert.rejects(tools.execute({ requestId: '1', name: 'stable_excel', args: { action: 'create' } }, 'read-only'), /只读/)
  await assert.rejects(tools.execute({ requestId: '2', name: 'stable_browser', args: { action: 'click', ref: '1' } }, 'workspace-write'), /审批/)
  await assert.rejects(tools.execute({ requestId: '3', name: 'stable_browser', args: { action: 'fill', ref: '1', value: 'x' }, approved: true }, 'read-only'), /只读/)
  tools.dispose()
})

test('built-in tools are wired into desktop and full/lightweight packaging', () => {
  const pkg = require('../package.json')
  const update = require('../build/update-builder.config.cjs')
  for (const config of [pkg.build, update]) assert.ok(config.extraResources.some(r => r.from === 'vendor/agent-tools' && r.to === 'agent-tools'))
  assert.ok(pkg.build.files.includes('desktop/**/*'))
  assert.match(fs.readFileSync(path.join(__dirname, '../desktop/main.cjs'), 'utf8'), /builtinTools: \(\) => new BuiltinTools/)
  assert.equal(require('../vendor/agent-tools/node_modules/exceljs/package.json').version, '4.4.0')
  const excelRequire = require('node:module').createRequire(require.resolve('../vendor/agent-tools/node_modules/exceljs'))
  const uuid = excelRequire('uuid')
  assert.match(uuid.v4(), /^[0-9a-f-]{36}$/)
  assert.throws(() => uuid.v5('fixture', uuid.v5.DNS, new Uint8Array(8), 4), RangeError)
  assert.equal(pkg.build.beforePack, 'scripts/verify-builtin-tools.cjs')
  require('../scripts/verify-builtin-tools.cjs')({ appDir: path.resolve(__dirname, '..') })
  assert.throws(() => require('../scripts/verify-builtin-tools.cjs')({ appDir: path.join(os.tmpdir(), 'stable-missing-tool-deps') }), /tools:install/)
  assert.match(fs.readFileSync(path.join(__dirname, '../.github/workflows/release.yml'), 'utf8'), /npm run tools:install/)
})

test('actual builder resource filters ship usable Excel dependencies in full and update layouts', async t => {
  const { FileMatcher, copyFiles } = require('app-builder-lib/out/fileMatcher.js')
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'stable-excel-package-'))
  t.after(() => fs.rmSync(root, { recursive: true, force: true }))
  const configs = [require('../package.json').build, require('../build/update-builder.config.cjs')]
  for (const [index, config] of configs.entries()) {
    const resources = path.join(root, String(index)); fs.mkdirSync(resources)
    const matches = config.extraResources.filter(item => item.to === 'agent-tools' || item.to.startsWith('agent-tools/'))
      .map(item => new FileMatcher(path.resolve(__dirname, '..', item.from), path.join(resources, item.to), value => value, item.filter))
    await copyFiles(matches, null, false)
    const result = await executeExcel({ workspace: resources, dependencyRoot: path.join(resources, 'agent-tools'),
      args: { action: 'create', output: 'packaged.xlsx', sheets: [{ name: 'Sheet', rows: [['packaged', 170]] }] } })
    assert.equal(result.verified, true)
    const book = new ExcelJS.Workbook(); await book.xlsx.readFile(result.path)
    assert.equal(book.getWorksheet('Sheet').getCell('B1').value, 170)
  }
})
