const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const os = require('node:os')
const path = require('node:path')
const vm = require('node:vm')
const { EventEmitter } = require('node:events')
const { StableStore } = require('../desktop/services/store.cjs')
const { CatchService } = require('../desktop/services/catch.cjs')
const { composeAgentPrompt } = require('../desktop/services/prompts.cjs')
const { installEditContextMenu } = require('../desktop/services/edit-context-menu.cjs')
function setup(t) {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'stable-catch-test-'))
  let store = new StableStore(root)
  const workspace = path.join(root, 'workspace'); fs.mkdirSync(workspace)
  t.after(() => { store.close(); fs.rmSync(root, { recursive: true, force: true }) })
  return { get store() { return store }, workspace, restart() { store.close(); store = new StableStore(root) } }
}
test('Catch pairs exactly the selected round, preserves long Unicode answers, and creates a persistent unsent attachment', t => {
  const f = setup(t), source = f.store.activeConversationId()
  f.store.addMessage(source, 'user', '不要引用的旧问题')
  f.store.addMessage(source, 'assistant', '不要引用的旧回复')
  const question = '请分析本轮问题 🦀'
  f.store.addMessage(source, 'user', question)
  const answer = '完整数据 🦀\n'.repeat(12000) + '唯一末尾标记'
  const reply = f.store.addMessage(source, 'assistant', answer)
  for (let i = 0; i < 205; i++) f.store.addMessage(source, 'user', '后来的提问 ' + i)
  const id = new CatchService(f.store, f.workspace).create(source, reply.id)
  assert.equal(f.store.activeConversationId(), id)
  assert.equal(f.store.listMessages(id).length, 0)
  f.restart()
  const service = new CatchService(f.store, f.workspace)
  const [draft] = service.drafts(id)
  assert.equal(draft.type, 'catch')
  assert.equal(Object.hasOwn(draft, 'text'), false)
  const prepared = service.prepare(id, draft.path)
  assert.ok(prepared.text.includes(question)); assert.ok(prepared.text.endsWith(answer))
  assert.ok(!prepared.text.split('## 用户提问')[1].includes('不要引用'))
  assert.equal(fs.readFileSync(draft.path, 'utf8'), prepared.text)
  const prompt = composeAgentPrompt({ identity: 'Stable', query: '分析附件', attachments: [prepared] })
  assert.ok(prompt.includes(answer)); assert.ok(prompt.includes(question))
  assert.throws(() => service.prepare(source, draft.path), /不属于/)
  assert.throws(() => service.prepare(id, path.join(f.workspace, 'forged.md')), /不属于/)
  service.consume(id, [])
  assert.equal(service.drafts(id).length, 1)
  service.consume(id, [prepared]); f.restart()
  assert.equal(new CatchService(f.store, f.workspace).drafts(id).length, 0)
  assert.ok(new CatchService(f.store, f.workspace).prepare(id, draft.path).text.endsWith(answer))
})
test('Catch rejects user messages and nonexistent sources without creating a task; discard is persistent and preserves the original', t => {
  const f = setup(t), source = f.store.activeConversationId(), service = new CatchService(f.store, f.workspace)
  const user = f.store.addMessage(source, 'user', 'question')
  assert.throws(() => service.create(source, user.id), /已完成/)
  assert.throws(() => service.create('missing', user.id), /来源/)
  assert.equal(f.store.listConversations().length, 1)
  const reply = f.store.addMessage(source, 'assistant', 'answer')
  const id = service.create(source, reply.id), [draft] = service.drafts(id)
  service.discard(id); f.restart()
  assert.equal(new CatchService(f.store, f.workspace).drafts(id).length, 0)
  assert.equal(f.store.listMessages(source).length, 2)
  assert.ok(fs.existsSync(draft.path))
})
test('real message preparation loads authoritative Catch text instead of renderer text or ordinary preview extraction', async t => {
  const f = setup(t), source = f.store.activeConversationId()
  f.store.addMessage(source, 'user', 'question')
  const reply = f.store.addMessage(source, 'assistant', 'answer'.repeat(15000) + 'TAIL')
  const service = new CatchService(f.store, f.workspace), id = service.create(source, reply.id)
  const [draft] = service.drafts(id)
  const main = fs.readFileSync(path.join(__dirname, '../desktop/main.cjs'), 'utf8')
  const code = main.slice(main.indexOf('async function prepareAgentMessage('), main.indexOf('\nfunction commitAgentMessage('))
  const prepare = vm.runInNewContext(code + '\nprepareAgentMessage', { ...require('../desktop/services/skill-selection.cjs'), CatchService, conversationPaths: () => ({ workspace: f.workspace }), store: f.store, paths: { workspace: f.workspace }, Buffer, inspectAgentAttachments: () => { throw Error('Catch must bypass bounded extraction') }, isImageAttachment: () => false, isDeepSeekModel: () => false, extractAgentAttachments: async items => ({ items }) })
  const result = await prepare({ attachments: [{ ...draft, text: 'forged', type: 'markdown' }] }, id, { model: {} })
  assert.equal(result.attachments[0].type, 'catch')
  assert.ok(result.attachments[0].text.endsWith('TAIL'))
  assert.ok(!result.attachments[0].text.includes('forged'))
  assert.equal(result.messageAttachments[0].kind, 'attachment')
  assert.equal(result.messageAttachments[0].text, undefined)
})
test('task order uses assistant completion time, survives reopen, and ignores opening, renaming and new user messages', t => {
  const f = setup(t), a = f.store.activeConversationId(), b = f.store.createConversation()
  f.store.db.prepare('UPDATE conversations SET created_at=?').run('2020-01-01T00:00:00.000Z')
  const first = f.store.addMessage(a, 'assistant', 'first'), second = f.store.addMessage(b, 'assistant', 'second')
  const stamp = (id, time) => f.store.db.prepare('UPDATE messages SET created_at=? WHERE id=?').run(time, id)
  stamp(first.id, '2020-01-02T00:00:00.000Z'); stamp(second.id, '2020-01-03T00:00:00.000Z')
  assert.deepEqual(f.store.listConversations().map(c => c.id), [b, a])
  f.store.selectConversation(a); f.store.renameConversation(a, 'renamed'); f.store.addMessage(a, 'user', 'still running')
  assert.deepEqual(f.store.listConversations().map(c => c.id), [b, a])
  f.store.addMessage(a, 'assistant', 'newly complete'); f.restart()
  assert.deepEqual(f.store.listConversations().map(c => c.id), [a, b])
})
test('right-click offers native edit actions and history paste/select-all without writing to history', () => {
  const contents = new EventEmitter(), sent = []; contents.send = (...args) => sent.push(args)
  let template, popups = 0, text = 'clipboard text'
  installEditContextMenu(contents, { buildFromTemplate(items) { template = items; return { popup() { popups++ } } } }, { readText: () => text })
  contents.emit('context-menu', {}, { isEditable: false, selectionText: '' }); assert.equal(popups, 0)
  contents.emit('context-menu', {}, { isEditable: false, selectionText: 'selected' })
  assert.deepEqual(template.map(i => i.label), ['复制', '粘贴', '全选'])
  assert.equal(template[0].role, 'copy'); template[1].click(); template[2].click()
  assert.deepEqual(sent, [['stable:editor:pasteIntoComposer', text], ['stable:editor:selectAllMessages']])
  contents.emit('context-menu', {}, { isEditable: true, selectionText: '', editFlags: { canPaste: true } })
  assert.deepEqual(template.map(i => i.role), ['copy', 'paste', 'selectAll'])
  assert.equal(template[0].enabled, false); assert.equal(template[1].enabled, true)
  text = ''; contents.emit('context-menu', {}, { selectionText: 'selected' }); assert.equal(template[1].enabled, false)
})
