const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os')
const {StableStore}=require('../desktop/services/store.cjs'),{SkillMarket}=require('../desktop/services/skill-market.cjs'),{ConversationLifecycle}=require('../desktop/services/conversation-lifecycle.cjs'),{ApprovalLedger,parseDecision}=require('../desktop/services/approval-ledger.cjs'),{approvalScope}=require('../desktop/services/codex-approval.cjs'),{sessionDirectory}=require('../desktop/services/codex-harness.cjs')
function fixture(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),'stable-v2-'));const store=new StableStore(root);t.after(()=>store.close());return {root,store,id:store.activeConversationId()}}
test('market CRUD persists complete content, enabled state, reference chip and no invented updates',async t=>{const {root,store}=fixture(t),m=new SkillMarket(store,root);const text='# Skill\n'+'长内容'.repeat(9000);m.save({name:'本地技能',content:text});let item=m.entries().find(i=>!i.builtin);assert.equal(item.content,text);m.toggle(item.id,false);assert.throws(()=>m.use(item.id),/启用/);m.toggle(item.id,true);const id=m.use(item.id);assert.equal(store.getSetting('draft-reference:'+id).id,item.id);await assert.rejects(m.checkUpdate(item.id),/没有配置/);assert.throws(()=>m.save({id:'../escape',name:'bad',content:'bad'}),/标识/);m.remove(item.id);assert(fs.existsSync(path.join(root,'market-skills',item.id,'SKILL.md')));assert(!m.entries().some(i=>i.id===item.id))})
test('reviewer requires exact digest and scope, stale/cancelled answers cannot change a decision',t=>{const {store,id}=fixture(t),ledger=new ApprovalLedger(store);const digest='a'.repeat(64),request=ledger.register({conversationId:id,runId:'run',source:{requestId:'1',actionDigest:digest},query:'读取报表',cwd:'E:/test'});const decision={decision:'approved',actionDigest:digest,approvedScope:digest,policyVersion:3,reasonCode:'user',rationale:'用户明确要求',authorizationBasis:'当前用户要求读取报表'};assert.equal(parseDecision(JSON.stringify(decision),digest).decision,'approved');assert.throws(()=>parseDecision(JSON.stringify({...decision,authorizationBasis:undefined}),digest));assert.throws(()=>parseDecision(JSON.stringify({...decision,approvedScope:'b'}),digest));ledger.cancelRun('run');assert.equal(ledger.finish(request.id,decision),false);store.grantConversationApproval(id,digest,'exact');assert(store.hasConversationApproval(id,digest));store.revokeConversationGrants(id);assert(!store.hasConversationApproval(id,digest))})
test('scope changes with script bytes and exact command arguments',t=>{const {root}=fixture(t),file=path.join(root,'query.py');fs.writeFileSync(file,'one');const p={cwd:root,command:'python "'+file+'" arg1'};const first=approvalScope('command',p,{category:'read'},{workspace:root});fs.writeFileSync(file,'two');assert.notEqual(first.key,approvalScope('command',p,{category:'read'},{workspace:root}).key);assert.notEqual(first.key,approvalScope('command',{...p,command:p.command+' arg2'},{category:'read'},{workspace:root}).key)})
test('delivery duplicates are rejected; reconciliation imports only a known final turn once, never starts a turn',async t=>{const {root,store,id}=fixture(t);const home=sessionDirectory(root,id);fs.mkdirSync(home,{recursive:true});fs.writeFileSync(path.join(home,'stable-thread.json'),JSON.stringify({threadId:'thread'}));const calls=[];const life=new ConversationLifecycle(store,{userData:root,executable:'mock',workspace:root,rpcFactory:()=>({request:async(method)=>{calls.push(method);return method==='thread/read'?{thread:{id:'thread',turns:[{id:'turn',status:'completed',items:[{id:'answer',type:'agentMessage',phase:'final_answer',text:'Recovered'}]}]}}:{}},close:async()=>{}})});life.begin('send',id,{text:'hello'});assert(life.begin('send',id,{text:'hello'}).duplicate);assert.throws(()=>life.begin('send',id,{text:'different'}),/冲突/);const message=store.addMessage(id,'user','hello');life.status('send','running',{userMessageId:message,threadId:'thread',turnId:'turn'});life.interrupted();assert.equal(life.deliveries(id)[0].state,'unknown');assert.equal((await life.reconcile(id)).added,1);assert.equal((await life.reconcile(id)).added,0);assert.equal(store.listMessages(id).filter(m=>m.role==='assistant').length,1);assert(!calls.includes('turn/start'));assert.equal((await life.sync(id,'archive')).pending,false);assert(store.conversation(id).archivedAt);assert.equal((await life.sync(id,'unarchive')).pending,false);assert(!store.conversation(id).archivedAt)})
test('runtime delete failure keeps messages and a retryable tombstone',async t=>{const {root,store,id}=fixture(t);store.addMessage(id,'user','Keep');const home=sessionDirectory(root,id);fs.mkdirSync(home,{recursive:true});fs.writeFileSync(path.join(home,'stable-thread.json'),JSON.stringify({threadId:'thread'}));let fail=true;const life=new ConversationLifecycle(store,{userData:root,executable:'mock',workspace:root,rpcFactory:()=>({request:async method=>{if(method==='thread/delete'&&fail)throw Error('offline');return {}},close:async()=>{}})});assert((await life.sync(id,'delete')).pending);assert.equal(store.listMessages(id)[0].content,'Keep');assert.equal(store.conversation(id).deletionState,'pending');fail=false;assert(!(await life.sync(id,'delete')).pending);assert(!store.conversation(id));assert(fs.existsSync(home))})

test('cleared history cannot be reimported by reconciliation and uncertain steer cannot be resent',async t=>{
 const {root,store,id}=fixture(t),home=sessionDirectory(root,id);fs.mkdirSync(home,{recursive:true});fs.writeFileSync(path.join(home,'stable-thread.json'),JSON.stringify({threadId:'thread'}));let starts=0
 const life=new ConversationLifecycle(store,{userData:root,executable:'mock',workspace:root,rpcFactory:()=>({request:async method=>{if(method==='turn/start')starts++;return method==='thread/read'?{thread:{id:'thread',turns:[{id:'turn',status:'completed',items:[{id:'answer',type:'agentMessage',text:'Old cleared answer'}]}]}}:{}},close:async()=>{}})})
 life.begin('request',id,{text:'old'});life.status('request','running',{threadId:'thread',turnId:'turn'});store.addMessage(id,'user','old');store.clearMessages(id);assert.equal((await life.reconcile(id)).added,0);assert.equal(store.listMessages(id).length,0);assert.equal(starts,0)
 assert.equal(life.beginSteer('steer',id,{query:'补充'}),'pending');life.interrupted();assert.throws(()=>life.beginSteer('steer',id,{query:'补充'}),e=>e.code==='STEER_UNCERTAIN');assert.equal(life.deliveries(id).find(d=>d.id==='steer').state,'unknown');life.saveSteer('steer','accepted','message');assert.equal(life.beginSteer('steer',id,{query:'补充'}),'accepted')
})

test('already deleted native thread is verified before completing a pending delete',async t=>{const {root,store,id}=fixture(t),home=sessionDirectory(root,id);fs.mkdirSync(home,{recursive:true});fs.writeFileSync(path.join(home,'stable-thread.json'),JSON.stringify({threadId:'thread'}));const calls=[];const life=new ConversationLifecycle(store,{userData:root,workspace:root,executable:'mock',rpcFactory:()=>({request:async method=>{calls.push(method);if(method==='initialize')return {};throw Object.assign(Error('thread not found'),{code:-32600})},close:async()=>{}})});assert.equal((await life.sync(id,'delete')).pending,false);assert(calls.includes('thread/read'));assert(!store.conversation(id));assert(!fs.existsSync(path.join(home,'stable-thread.json')))})
