const test = require('node:test')
const assert = require('node:assert/strict')
const { readFileSync } = require('node:fs')
const path = require('node:path')
const source = (file) => readFileSync(path.join(__dirname, '..', file), 'utf8')

test('composer stop is a black circle with white square and send has no blue background', () => {
  const css = source('src/styles/app.css')
  const tokens = source('src/styles/tokens.css')
  assert.match(tokens, /--color-composer-stop: #000;/)
  assert.match(tokens, /--color-composer-stop-icon: #fff;/)
  assert.match(css, /\.composer-stop \.composer-action-visual \{[^}]*background: var\(--color-composer-stop\);[^}]*color: var\(--color-composer-stop-icon\)/)
  for (const rule of css.matchAll(/\.composer-(?:send|stop)(?::(?:hover|active))?\s*\{([^}]+)\}/g)) assert.doesNotMatch(rule[1], /--color-accent|--color-error/)
  assert.match(css, /\.composer-send \{[^}]*background: transparent/)
  assert.match(css, /\.composer-send:hover:not\(:disabled\) \{[^}]*background: transparent/)
  assert.match(css, /\.composer-send:active \{[^}]*background: transparent/)
  assert.match(css, /\.composer-send:disabled \{[^}]*background: transparent; color: var\(--color-muted\)/)
  assert.match(source('src/App.tsx'), /<svg[^>]*aria-hidden="true"><rect[^>]*fill="currentColor"/)
})

test('one composer action stops only when running without content and otherwise shows send', () => {
  const app = source('src/App.tsx')
  assert.match(app, /const hasComposerContent = Boolean\(prompt.trim\(\) \|\| attachments.length \|\| selectedReferences.length\)/)
  assert.match(app, /const showComposerStop = running && !hasComposerContent/)
  assert.match(app, /className=\{showComposerStop \? 'composer-stop' : 'composer-send'\}/)
  assert.match(app, /onClick=\{showComposerStop \? stopConversation : send\}/)
  assert.match(app, /disabled=\{!hasComposerContent && !running\}/)
  assert.doesNotMatch(app, /className="composer-send"|className="composer-stop"/)
  assert.match(app, /请输入内容或添加附件后发送/)
})

test('composer visuals shrink 25 percent without shrinking the click target or changing alignment', () => {
  const css = source('src/styles/app.css')
  assert.match(css, /\.composer-action-visual \{[^}]*width: 100%; height: 100%;[^}]*transform: scale\(\.75\); pointer-events: none/)
  assert.match(css, /\.composer-stop \{[^}]*width: var\(--control-height\); height: var\(--control-height\);[^}]*background: transparent/)
  assert.match(css, /\.composer-actions \{[^}]*align-items: center; gap: var\(--space-xs\)/)
  assert.match(source('src/App.tsx'), /className="composer-action-visual" aria-hidden="true"/)
})

test('composer stays editable while running and keeps queue control separate from stopping', () => {
  const app = source('src/App.tsx')
  const input = app.slice(app.indexOf('<textarea ref={promptRef}'), app.indexOf('<div className="composer-actions">'))
  assert.doesNotMatch(input, /disabled=/)
  assert.match(input, /!event.nativeEvent.isComposing/)
  assert.match(app, /aria-label="待发送消息"/)
  assert.match(app, /outbox\.enqueue\(conversationId/)
  assert.match(app, /attachments: attachments\.map/)
  assert.match(app, /references: selectedReferences\.map/)
  assert.match(app, /outbox\.pause\(activeConversation\.id\)[\s\S]*agent\.cancel/)
  assert.match(app, /!pendingQueue.running && !pendingQueue.items.length/)
  assert.match(app, /savedTraceStatus\(lastAnswer.trace\) === 'completed'/)
})

test('steering uses a separate IPC bridge and reserves a run before preparing attachments', () => {
  const main = source('desktop/main.cjs')
  const run = main.slice(main.indexOf("ipcMain.handle('stable:agent:run'"), main.indexOf("ipcMain.handle('stable:agent:steer'"))
  const steer = main.slice(main.indexOf("ipcMain.handle('stable:agent:steer'"), main.indexOf("ipcMain.handle('stable:agent:cancel'"))
  assert.ok(run.indexOf('agentRunners.set') < run.indexOf('await prepareAgentMessage'))
  assert.match(run, /control.cancelled/)
  assert.match(steer, /prepareAgentMessage\(payload, conversationId, control.modelRoute\)/)
  assert.match(steer, /steerRequests.get\(requestId\)/)
  assert.match(steer, /error.code !== 'STEER_UNCERTAIN'/)
  assert.ok(steer.indexOf('await control.runner.steer') < steer.indexOf('commitAgentMessage'))
  assert.doesNotMatch(steer, /runner.cancel\(|createHarnessRunner\(|runAgent\(/)
  assert.match(source('desktop/preload.cjs'), /steer:.*invoke\('stable:agent:steer'/)
})
