'use strict'

const test = require('node:test')
const assert = require('node:assert/strict')
const { readFileSync } = require('node:fs')
const path = require('node:path')

const root = path.join(__dirname, '..')
const app = readFileSync(path.join(root, 'src', 'App.tsx'), 'utf8')
const css = readFileSync(path.join(root, 'src', 'styles', 'app.css'), 'utf8')
const preload = readFileSync(path.join(root, 'desktop', 'preload.cjs'), 'utf8')
const main = readFileSync(path.join(root, 'desktop', 'main.cjs'), 'utf8')

test('work and lab navigation split existing modules while repository keeps four real pages', () => {
  assert.match(app, /className="rail-mode-switch"/)
  assert.match(app, /<span>工作<\/span>/)
  assert.match(app, /<span>实验室<\/span>/)
  assert.match(app, /const LAB_NAV[\s\S]*'workflows'[\s\S]*'team'/)
  assert.match(app, /const REPOSITORY_TABS[\s\S]*'data'[\s\S]*'reports'[\s\S]*'skills'[\s\S]*'knowledge'/)
  assert.match(app, /function RepositoryPage/)
  assert.match(css, /\.repository-tabs/)
  assert.doesNotMatch(app, /className="brand-mark"/)
  assert.doesNotMatch(app, /stable_logo_sidebar_(?:dark|light)\.png/)
  assert.match(css, /\.rail-mode-switch\s*\{[^}]*width:\s*52\.5%[^}]*margin-inline:\s*0 auto[^}]*padding:\s*0\.1875rem/)
  assert.match(css, /\.rail-mode-switch button\s*\{[^}]*min-height:\s*2\.25rem[^}]*font-size:\s*var\(--text-xs\)/)
  assert.match(app, /<BriefcaseBusiness size=\{14\}/)
  assert.match(app, /<FlaskConical size=\{14\}/)
})

test('sidebar width is session-only, pointer resizable, and keyboard accessible', () => {
  assert.match(app, /const \[railWidth, setRailWidth\] = useState\(DEFAULT_RAIL_WIDTH\)/)
  assert.match(app, /className="rail-resizer"/)
  assert.match(app, /role="separator"/)
  assert.match(app, /aria-valuenow=\{Math\.round\(railWidth\)\}/)
  assert.match(app, /ArrowLeft: -16, ArrowRight: 16/)
  assert.match(app, /onDoubleClick=\{\(\) => setRailWidth\(clampRailWidth\(DEFAULT_RAIL_WIDTH\)\)\}/)
  assert.doesNotMatch(app, /localStorage[\s\S]{0,120}railWidth|railWidth[\s\S]{0,120}localStorage/)
  assert.match(css, /\.rail-resizer\s*\{[^}]*cursor:\s*col-resize[^}]*touch-action:\s*none/)
  assert.match(css, /\.rail-resizer:focus-visible::after/)
})

test('account dock stays at the bottom and main content has a rounded top-left junction', () => {
  assert.match(css, /\.rail-account-dock\s*\{[^}]*margin-block-start:\s*auto/)
  assert.match(css, /\.main-frame\s*\{[^}]*border-start-start-radius:\s*var\(--radius-lg\)[^}]*background:\s*var\(--color-paper\)/)
  assert.match(app, /if \(!onToggleRail \|\| !onSearch\) return <div className="window-titlebar" aria-hidden="true" \/>/)
  assert.match(main, /dark: \{ backgroundColor: '#060d15'/)
  assert.match(main, /light: \{ backgroundColor: '#f3eee6'/)
})

test('titlebar can fully collapse the rail and search titles plus all conversation messages', () => {
  const titlebar = app.slice(app.indexOf('function WindowTitlebar'), app.indexOf('function ConversationSearch'))
  assert.match(app, /const \[railCollapsed, setRailCollapsed\] = useState\(false\)/)
  assert.match(app, /data-rail-collapsed=\{railCollapsed \|\| undefined\}/)
  assert.match(app, /!railCollapsed && <aside/)
  assert.match(app, /!railCollapsed && <div\s*className="rail-resizer"/)
  assert.ok(titlebar.indexOf('PanelLeftClose') < titlebar.indexOf('<Search size={17}'))
  assert.match(titlebar, /aria-label=\{railCollapsed \? '展开侧边导航栏' : '收起侧边导航栏'\}/)
  assert.match(titlebar, /aria-label="搜索对话记录"/)
  assert.match(app, /搜索对话标题和全部消息内容/)
  assert.match(app, /placeholder="输入标题或消息关键词"/)
  assert.match(app, /if \(event\.key === 'Escape'\)/)
  assert.match(app, /window\.stable\.agent\.search\(conversationSearchQuery\)/)
  assert.match(app, /setPage\('agent'\)/)
  assert.match(css, /\.app-shell\[data-rail-collapsed="true"\]\s*\{[^}]*grid-template-columns:\s*0 minmax\(0, 1fr\)/)
  assert.match(css, /\.main-frame\s*\{[^}]*grid-column:\s*2/)
  assert.match(css, /\.conversation-search-dialog\s*\{[^}]*width:\s*min\(31rem/)
  assert.match(preload, /search:\s*\(query\) => invoke\('stable:agent:search'/)
  assert.match(main, /ipcMain\.handle\('stable:agent:search'/)
  assert.match(main, /store\.searchConversations\(payload\.query, 30\)/)
})

test('conversation task list exposes persistent pinning and a guarded action menu', () => {
  assert.match(app, /createPortal\(<ConversationTaskSections \/>, conversationTasksTarget\)/)
  assert.match(app, /className="rail-conversation-tasks-slot"/)
  assert.match(app, /aria-label="任务清单"/)
  assert.match(app, /aria-label="置顶任务"/)
  assert.match(app, /className="conversation-pin-action"/)
  assert.match(app, /openConversation=\{\(\) => setPage\('agent'\)\}/)
  assert.match(app, /function selectConversation\(item: ConversationItem\)/)
  assert.match(main, /STABLE_QA_OPEN_CONVERSATION_FROM_TAB/)
  assert.match(app, /className="conversation-action-menu" role="menu"/)
  assert.match(app, /state\.conversations\.filter\(\(item\) => !item\.pinned\)\.map/)
  assert.match(app, /在资源管理器打开/)
  assert.match(app, /<span>文件管理<\/span><small>暂不可用<\/small>/)
  assert.match(app, /<span>分享<\/span><small>暂不可用<\/small>/)
  assert.match(preload, /stable:agent:pin/)
  assert.match(main, /store\.setConversationPinned/)
  assert.match(css, /\.rail-conversation-tasks-slot/)
  assert.match(css, /\.rail-conversation-tasks-slot \.conversation-list[^}]*overflow:\s*visible/)
  assert.doesNotMatch(css, /\.conversation-pinned[^}]*max-height/)
  assert.match(css, /\.conversation-action-menu\s*\{[^}]*width:\s*11\.9rem[^}]*background:\s*var\(--color-paper\)[^}]*box-shadow:\s*var\(--shadow-float\) !important/)
  assert.match(css, /#root \.conversation-history-card \.conversation-list-item\[data-active="true"\][^{]*\{ background: var\(--color-paper-4\) !important; \}/)
  assert.match(css, /\.conversation-sidebar-mobile\s*\{\s*display:\s*none/)
})

test('file cards open in Stable and expose a compact context menu with HTML-only external browsing', () => {
  assert.match(app, /onContextMenu=\{openContextMenu\}/)
  assert.match(app, /className="conversation-file-menu" role="menu"/)
  assert.match(app, /打开文件所在位置/)
  assert.match(app, /isHtml && <button[^>]*role="menuitem"[\s\S]*用外部浏览器打开/)
  assert.match(preload, /stable:system:openExternalHtml/)
  assert.match(main, /stable:system:openExternalHtml/)
  assert.match(main, /const openError = await shell\.openPath\(resolved\.path\)/)
  assert.match(app, /className="conversation-file-error" role="alert"/)
  assert.match(main, /STABLE_QA_FILE_CONTEXT_MENU/)
  assert.match(css, /\.conversation-file-menu\s*\{[^}]*position:\s*fixed[^}]*box-shadow:\s*var\(--shadow-float\) !important/)
})

test('update badge is driven by the manual-download updater state', () => {
  assert.match(app, /const updateReady = \['available', 'downloading', 'downloaded'\]/)
  assert.match(app, /className="update-dot"/)
  assert.match(app, /window\.stable\.updater\.download\(\)/)
  assert.match(preload, /stable:update:download/)
  assert.match(css, /\.rail-account-trigger > \.update-dot/)
})

test('account trigger combines the avatar and display name in one rounded control', () => {
  assert.match(app, /className="rail-account-name">\{displayName\}<\/span>/)
  assert.match(css, /\.rail-account-trigger\s*\{[^}]*grid-template-columns:\s*auto minmax\(0, 1fr\)/)
  assert.match(css, /\.rail-account-name\s*\{/)
})
