'use strict'

const test = require('node:test')
const assert = require('node:assert/strict')
const { mkdtempSync, mkdirSync, readFileSync, rmSync, symlinkSync, writeFileSync } = require('node:fs')
const os = require('node:os')
const path = require('node:path')
const { normalizeWebUrl, renderMarkdownDocument, renderTextDocument, resolveMarkdownFile, resolveWorkspaceEntry } = require('../desktop/services/preview.cjs')

const root = path.resolve(__dirname, '..')

test('web preview accepts only credential-free HTTP and HTTPS URLs', () => {
  assert.equal(normalizeWebUrl('https://example.com/docs'), 'https://example.com/docs')
  assert.equal(normalizeWebUrl('http://127.0.0.1:3000'), 'http://127.0.0.1:3000/')
  assert.throws(() => normalizeWebUrl('file:///C:/secret.txt'), /只支持 HTTP 或 HTTPS/)
  assert.throws(() => normalizeWebUrl('https://user:secret@example.com'), /不能包含账号或密码/)
  assert.throws(() => normalizeWebUrl('javascript:alert(1)'), /只支持 HTTP 或 HTTPS/)
})

test('file preview accepts only canonical entries that remain inside the Stable workspace', () => {
  const temporary = mkdtempSync(path.join(os.tmpdir(), 'stable-preview-'))
  try {
    const workspace = path.join(temporary, 'workspace')
    const outside = path.join(temporary, 'outside')
    const sibling = path.join(temporary, 'workspace-copy')
    mkdirSync(workspace); mkdirSync(outside); mkdirSync(sibling)
    const trustedFile = path.join(workspace, 'trusted.md')
    const outsideFile = path.join(outside, 'outside.md')
    const siblingFile = path.join(sibling, 'sibling.md')
    writeFileSync(trustedFile, '# Trusted', 'utf8')
    writeFileSync(outsideFile, '# Outside', 'utf8')
    writeFileSync(siblingFile, '# Sibling', 'utf8')
    assert.equal(resolveWorkspaceEntry(trustedFile, workspace, { fileOnly: true }).path, trustedFile)
    assert.equal(resolveMarkdownFile(trustedFile, workspace).content, '# Trusted')
    assert.throws(() => resolveWorkspaceEntry(outsideFile, workspace), /工作区内真实存在/)
    assert.throws(() => resolveWorkspaceEntry(siblingFile, workspace), /工作区内真实存在/)
    assert.throws(() => resolveWorkspaceEntry(path.join(outside, 'missing.md'), workspace), /工作区内真实存在/)
    assert.throws(() => resolveWorkspaceEntry(path.join(workspace, 'missing.md'), workspace), /不存在/)
    assert.throws(() => resolveWorkspaceEntry(workspace, workspace, { fileOnly: true }), /只能预览文件/)

    const jump = path.join(workspace, 'jump')
    symlinkSync(outside, jump, process.platform === 'win32' ? 'junction' : 'dir')
    assert.throws(() => resolveWorkspaceEntry(path.join(jump, 'outside.md'), workspace), /工作区内真实存在/)
  } finally {
    rmSync(temporary, { recursive: true, force: true })
  }
})

test('Markdown rendering escapes embedded HTML and applies a restrictive CSP', () => {
  const html = renderMarkdownDocument('# 标题\n\n<script>alert("x")</script>\n\n- **安全**\n- `code`\n\n| 列 | 值 |\n| --- | --- |\n| A | 1 |', 'demo.md')
  assert.match(html, /Content-Security-Policy/)
  assert.match(html, /default-src 'none'/)
  assert.match(html, /&lt;script&gt;alert\(&quot;x&quot;\)&lt;\/script&gt;/)
  assert.doesNotMatch(html, /<script>/)
  assert.match(html, /<table>/)
})

test('text preview escapes file content and cannot load active resources', () => {
  const html = renderTextDocument('<img src="https://example.com/leak"><script>alert(1)</script>', 'unsafe.html', 'dark', { path: 'D:\\workspace\\unsafe.html', size: 42, type: 'HTML' })
  assert.match(html, /default-src 'none'/)
  assert.match(html, /&lt;img src=&quot;https:\/\/example\.com\/leak&quot;&gt;/)
  assert.match(html, /&lt;script&gt;alert\(1\)&lt;\/script&gt;/)
  assert.doesNotMatch(html, /<script>/)
})

test('Electron side preview separates web and workspace sessions, blocks local scripts and ignores superseded views', () => {
  const main = readFileSync(path.join(root, 'desktop', 'main.cjs'), 'utf8')
  const preload = readFileSync(path.join(root, 'desktop', 'preload.cjs'), 'utf8')
  const pkg = JSON.parse(readFileSync(path.join(root, 'package.json'), 'utf8'))
  assert.match(main, /new WebContentsView/)
  assert.match(main, /'stable-preview-web' : 'stable-preview-local'/)
  assert.match(main, /contextIsolation: true/)
  assert.match(main, /nodeIntegration: false/)
  assert.match(main, /sandbox: true/)
  assert.match(main, /webSecurity: true/)
  assert.match(main, /javascript: kind === 'web'/)
  assert.match(main, /webviewTag: false/)
  assert.match(main, /navigateOnDragDrop: false/)
  assert.match(main, /setPermissionCheckHandler\(\(\) => false\)/)
  assert.match(main, /setPermissionRequestHandler[\s\S]*callback\(false\)/)
  assert.match(main, /setWindowOpenHandler[\s\S]*return \{ action: 'deny' \}/)
  assert.match(main, /sourceView !== previewView/)
  assert.match(main, /function requireActivePreviewView\(view\)/)
  assert.match(main, /previewView !== view \|\| view\.webContents\.isDestroyed\(\)/)
  assert.match(main, /const view = previewView\s+previewView = undefined\s+previewKind = undefined\s+cleanupPreviewTemporaryFile\(\)/)
  assert.match(main, /isAllowedLocalPreviewRequest/)
  assert.match(main, /isAllowedLocalPreviewNavigation/)
  assert.match(main, /if \(url\.hostname\) return false/)
  assert.match(main, /sameFilesystemPath\(requested, previewTemporaryPath\)[\s\S]*existsSync\(requested\) && statSync\(requested\)\.isFile\(\)/)
  assert.match(main, /resolveWorkspaceEntry\(requested, paths\.workspace, \{ fileOnly: true \}\)/)
  assert.match(main, /if \(protocol === 'data:' \|\| protocol === 'blob:'\) return true/)
  assert.match(main, /function isAllowedLocalPreviewNavigation\(value\) \{\s*return isAllowedWorkspacePreviewFile\(value\)/)
  assert.match(main, /contentView\.addChildView\(view\)/)
  assert.match(main, /view\.setBounds\(normalizedPreviewBounds\(bounds\)\)/)
  assert.match(main, /stable:preview:openFile/)
  assert.match(main, /const resolved = resolveWorkspaceEntry\(value, paths\.workspace\)/)
  assert.match(main, /renderFileInfoDocument\(resolved, theme, `Stable 无法渲染这个 Markdown 文件/)
  assert.match(main, /const resolved = resolveWorkspaceEntry\(requested, paths\.workspace\)/)
  assert.match(preload, /stable:preview:openWeb/)
  assert.match(preload, /stable:preview:openFile/)
  assert.match(preload, /stable:preview:setBounds/)
  assert.match(preload, /stable:preview:close/)
  assert.doesNotMatch(main, /stable:preview:openMarkdown|isConversationPreviewPath/)
  assert.doesNotMatch(main, /previewRequestFromArgv|previewCliInstruction/)
  assert.ok(!pkg.build.extraResources.some((item) => item.from === 'scripts/stable-preview.cjs'))
})
