const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const JSZip = require('jszip')
const { StableStore } = require('../desktop/services/store.cjs')
const { installWorkspaceSkill } = require('../desktop/services/skill-install.cjs')
test('ZIP install persists all files and rejects invalid sources', async () => {
  const root = path.resolve(__dirname, '../qa-artifacts/skill-install', String(Date.now()))
  const workspace = path.join(root, 'workspace'), userData = path.join(root, 'profile')
  fs.mkdirSync(workspace, { recursive: true })
  const store = new StableStore(userData)
  const install = (source, signal) => installWorkspaceSkill({ source, workspace, userData, store, signal })
  try {
    const zip = new JSZip()
    zip.file('demo/SKILL.md', '---\nname: demo\ndescription: Test\n---\n# demo')
    zip.file('demo/assets/test.bin', Buffer.from([0, 255, 2]))
    const source = path.join(workspace, 'demo.zip')
    const bytes = await zip.generateAsync({ type: 'nodebuffer' })
    fs.writeFileSync(source, bytes)
    const result = await install(source)
    assert(result.path.startsWith(path.join(userData, 'skills')))
    assert.deepEqual(fs.readFileSync(path.join(result.path, 'assets/test.bin')), Buffer.from([0, 255, 2]))
    assert.deepEqual(fs.readFileSync(source), bytes)
    assert.equal((await install(source)).alreadyInstalled, true)
    assert.equal(store.listSkills().length, 1)
    await assert.rejects(install(userData), /工作区/)
    await assert.rejects(install(source, AbortSignal.abort()), /abort/i)
    const bad = new JSZip()
    bad.file('a/SKILL.md', 'a'); bad.file('b/SKILL.md', 'b')
    const badPath = path.join(workspace, 'many.zip')
    fs.writeFileSync(badPath, await bad.generateAsync({ type: 'nodebuffer' }))
    await assert.rejects(install(badPath), /唯一/)
    for (const [name, options] of [['../escape/SKILL.md', {}], ['file:stream', {}], ['link', { unixPermissions: 0o120777 }]]) {
      const invalid = new JSZip(); invalid.file('SKILL.md', 'demo'); invalid.file(name, 'bad', options)
      fs.writeFileSync(badPath, await invalid.generateAsync({ type: 'nodebuffer', platform: 'UNIX' }))
      await assert.rejects(install(badPath), /不安全|符号链接/)
    }
    assert.deepEqual(fs.readdirSync(path.join(userData, 'skill-import-staging')), [])
    const folder = path.join(workspace, 'new-skill'); fs.mkdirSync(folder)
    fs.writeFileSync(path.join(folder, 'SKILL.md'), '---\nname: rollback\ndescription: test\n---\n# new')
    const before = fs.readdirSync(path.join(userData, 'skills'))
    store.upsertSkill = () => { throw Error('registration failed') }
    await assert.rejects(install(folder), /registration failed/)
    assert.deepEqual(fs.readdirSync(path.join(userData, 'skills')), before)
  } finally { store.db.close() }
})

test('installer requires approval, rejects read-only and never runs before approval', async () => {
  const { BuiltinTools } = require('../desktop/services/builtin-tools.cjs')
  let count = 0
  const tools = new BuiltinTools({ workspace: __dirname, browserSession: {}, installSkill: async () => { count++; return { installed: true } } })
  const request = { requestId: 'install', name: 'stable_skill_install', args: { path: __dirname } }
  await assert.rejects(tools.execute(request, 'workspace-write'), /审批/)
  await assert.rejects(tools.execute({ ...request, approved: true }, 'read-only'), /只读/)
  assert.equal(count, 0)
  assert.equal((await tools.execute({ ...request, approved: true }, 'workspace-write')).installed, true)
  assert.equal(count, 1)
  tools.dispose()
})
