import { useEffect, useRef, useState } from 'react'
import { ArrowLeft, ArrowRight, Plus, RotateCw, X, Download, History, Hand, MousePointer2 } from 'lucide-react'
type Tab = { id:string; title:string; url:string; state:string; error?:string; blockedURL?:string; diagnostics:boolean;blockedSites?:string[] }
export function BrowserPanel({ conversationId, initialURL, onClose, onImport, obscured }: { conversationId:string; initialURL?:string; obscured?:boolean; onClose:()=>void; onImport:(value:any)=>void }) {
  const [state,setState]=useState<{tabs:Tab[];activeTabId?:string;downloads:any[]}>({tabs:[],downloads:[]})
  const [url,setURL]=useState(''),[error,setError]=useState(''),[section,setSection]=useState('page'),[history,setHistory]=useState<any>({history:[],annotations:[]}),[settings,setSettings]=useState<any>({}),[note,setNote]=useState('')
  const viewport=useRef<HTMLDivElement>(null),mounted=useRef(true),initial=useRef(initialURL)
  const tab=state.tabs.find(t=>t.id===state.activeTabId)
  const api=(action:string,rest:Record<string,unknown>={})=>window.stable.browser.command({conversationId,action,...rest})
  const refresh=async()=>{const next=await api('state');if(mounted.current)setState(next)}
  const perform=async(action:string,rest:Record<string,unknown>={})=>{try{setError('');const result=await api(action,rest);if(result?.tabs)setState(result);return result}catch(e){setError(e instanceof Error?e.message:String(e))}}
  useEffect(()=>{mounted.current=true;void (async()=>{try{await refresh();if(initial.current){await api('create',{url:initial.current});initial.current=undefined;await refresh()}}catch(e){setError(String(e))}})();const off=window.stable.browser.onChanged(()=>{void refresh().catch(()=>{})});return()=>{mounted.current=false;off();void api('hide')}},[conversationId])
  useEffect(()=>{setURL(tab?.url==='about:blank'?'':tab?.url||'')},[tab?.id,tab?.url])
  useEffect(()=>{const element=viewport.current;if(!element||!tab||section!=='page'||obscured){void api('hide');return}const show=()=>{const r=element.getBoundingClientRect();void api('show',{tabId:tab.id,bounds:{x:r.x,y:r.y,width:r.width,height:r.height}}).catch(e=>setError(String(e)))};show();const observer=new ResizeObserver(show);observer.observe(element);window.addEventListener('resize',show);return()=>{observer.disconnect();window.removeEventListener('resize',show);void api('hide')}},[tab?.id,section,conversationId,obscured])
  async function viewSection(next:string){setSection(next);if(next==='history')setHistory(await perform('history')||{history:[],annotations:[]});if(next==='downloads')setSettings(await perform('settings')||{})}
  return <aside className="shared-browser" aria-label="共享浏览器">
    <header><strong>浏览器</strong><span>当前对话</span><button onClick={()=>void perform('create')} aria-label="新标签页"><Plus size={16}/></button><button onClick={onClose} aria-label="收起浏览器"><X size={16}/></button></header>
    <div className="browser-tabs">{state.tabs.map(t=><div key={t.id} data-active={t.id===tab?.id}><button onClick={()=>setState(s=>({...s,activeTabId:t.id}))}>{t.title||'新标签页'}</button><button aria-label="关闭标签页" onClick={()=>void perform('close',{tabId:t.id})}>×</button></div>)}</div>
    <form className="browser-address" onSubmit={e=>{e.preventDefault();void (tab?perform('navigate',{tabId:tab.id,navigation:'open',url}):perform('create',{url}));setSection('page')}}>
      <button type="button" aria-label="后退" onClick={()=>void perform('navigate',{tabId:tab?.id,navigation:'back'})}><ArrowLeft size={16}/></button><button type="button" aria-label="前进" onClick={()=>void perform('navigate',{tabId:tab?.id,navigation:'forward'})}><ArrowRight size={16}/></button><button type="button" aria-label="重新加载" onClick={()=>void perform('navigate',{tabId:tab?.id,navigation:'reload'})}><RotateCw size={16}/></button><input aria-label="网页地址" value={url} onChange={e=>setURL(e.target.value)} placeholder="输入网址"/><button type="submit">前往</button>
    </form>
    <nav><button onClick={()=>void viewSection('page')}>页面</button><button onClick={()=>void viewSection('downloads')}><Download size={15}/>下载</button><button onClick={()=>void viewSection('history')}><History size={15}/>历史与批注</button>{tab&&<button className="browser-control" onClick={()=>void perform('control',{tabId:tab.id,user:tab.state!=='user_controlled'})}>{tab.state==='user_controlled'?<><MousePointer2 size={15}/>交还模型</>:<><Hand size={15}/>接管 / 登录</>}</button>}</nav>
    {error&&<p role="alert">{error}</p>}{tab?.state==='user_controlled'&&<p className="browser-notice">你正在控制页面。模型已暂停读取和操作；完成后点击“交还模型”。</p>}
    {section==='page'&&<>{tab?.blockedSites?.map(origin=><p key={origin}>此页面请求了新的站点：{origin}<button onClick={()=>void perform('permitSite',{origin})}>允许此站点</button></p>)}{tab?.error&&<p>{tab.error}{tab.blockedURL&&<button onClick={()=>void perform('navigate',{tabId:tab.id,navigation:'open',url:tab.blockedURL})}>允许访问 {(()=>{try{return new URL(tab.blockedURL).hostname}catch{return '网站'}})()}</button>}</p>}<div className="browser-viewport" ref={viewport}>{!tab&&<p>打开新标签页，或等待模型打开网页。</p>}</div></>}
    {section==='downloads'&&<div className="browser-records"><p>下载目录：{settings.directory||settings.defaultDirectory}<button onClick={()=>void perform('settings',{chooseDirectory:true}).then(s=>s&&setSettings(s))}>更改</button></p><label><input type="checkbox" checked={Boolean(settings.askEach)} onChange={e=>void perform('settings',{askEach:e.target.checked}).then(s=>s&&setSettings(s))}/>每次询问保存位置</label>{state.downloads.map(d=><article key={d.id}><strong>{d.name}</strong><p>{({completed:'已完成',downloading:'下载中',cancelled:'已取消',failed:'失败',interrupted:'中断',awaiting_permission:'等待下载许可',awaiting_location:'等待保存位置'} as Record<string,string>)[d.state]||d.state} · {d.receivedBytes} / {d.totalBytes||'未知'} 字节</p>{d.totalBytes>0&&<progress value={d.receivedBytes} max={d.totalBytes}/>}<p>{d.error}</p>{d.state==='completed'?<><button onClick={()=>void perform('revealDownload',{downloadId:d.id})}>文件位置</button><button onClick={()=>void perform('importDownload',{downloadId:d.id}).then(a=>a&&onImport(a))}>作为任务附件</button></>:<><button onClick={()=>void perform('cancelDownload',{downloadId:d.id})}>取消下载</button>{d.state==='awaiting_permission'&&<button onClick={()=>void perform('allowDownload',{downloadId:d.id})}>允许此次下载</button>}</>}</article>)}</div>}
    {section==='history'&&<div className="browser-records"><label><input type="checkbox" checked={Boolean(history.allowHistory)} onChange={e=>{const enabled=e.target.checked;void perform('allowHistory',{enabled});setHistory((h:any)=>({...h,allowHistory:enabled}))}}/>允许模型读取此对话的浏览历史</label><button onClick={()=>void perform('clearHistory').then(()=>viewSection('history'))}>清空此对话历史</button><button onClick={()=>void perform('revokeSites')}>撤销网站许可</button>{tab&&<><label><input type="checkbox" checked={tab.diagnostics} onChange={e=>void perform('diagnostics',{tabId:tab.id,enabled:e.target.checked})}/>允许此标签页的控制台诊断</label><textarea aria-label="页面批注" value={note} onChange={e=>setNote(e.target.value)} placeholder="为当前页面添加批注"/><button onClick={()=>void perform('annotate',{tabId:tab.id,text:note}).then(()=>{setNote('');void viewSection('history')})}>保存批注</button></>}{history.annotations.map((a:any)=><article key={a.id}><strong>{a.text}</strong><p>{a.url}</p></article>)}{history.history.map((h:any)=><article key={h.id}><button onClick={()=>{void perform('create',{url:h.url});setSection('page')}}>{h.title}</button><p>{h.url} · {h.time}</p></article>)}</div>}
  </aside>
}
